spring:
  application:
    name: citronix
  datasource:
    url: jdbc:postgresql://localhost:1230/postgres
    username: postgres
    password: 1230
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
